[2018-12-10T10:40:57.924] [ERROR] dateFileLog - Error: Cannot GET /biz/API/getMESInfoTest?OID%5B0%5D=333&amp;OID%5B1%5D=444&amp;_=1544409657784

    at D:\work\MESAPI\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-10T10:43:01.146] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.engine.sqlserver.js:105:22)<br> &nbsp; &nbsp;at module.exports (D:\work\MESAPI\mesAPI\biz\API\getPrdMKOrdMain.{m}.js:34:17)<br> &nbsp; &nbsp;at buildData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\MESAPI\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\MESAPI\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-10T10:43:02.632] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.engine.sqlserver.js:105:22)<br> &nbsp; &nbsp;at module.exports (D:\work\MESAPI\mesAPI\biz\API\getPrdMKOrdMain.{m}.js:34:17)<br> &nbsp; &nbsp;at buildData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\MESAPI\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\MESAPI\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\MESAPI\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-10T13:33:28.088] [ERROR] dateFileLog - Error: 'config.security.isNeedSession' must set to true.
    at module.exports (D:\work\MESAPI\yujiang.Foil.Node.WebServer\app\account\showLogin.{get}.{m}.js:4:16)
    at buildData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:187:6)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:129:5
    at Object.module.exports.read (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)
    at loadData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:123:15)
    at rrnmv (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:120:2)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:223:4
    at Layer.handle [as handle_request] (D:\work\MESAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\work\MESAPI\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\work\MESAPI\node_modules\express\lib\router\route.js:112:3)
[2018-12-10T14:24:50.711] [ERROR] dateFileLog - { Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjApp.js:218:14
    at D:\work\MESAPI\node_modules\async\lib\async.js:610:21
    at D:\work\MESAPI\node_modules\async\lib\async.js:249:17
    at iterate (D:\work\MESAPI\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (D:\work\MESAPI\node_modules\async\lib\async.js:165:9)
    at _asyncMap (D:\work\MESAPI\node_modules\async\lib\async.js:248:13)
    at Object.mapSeries (D:\work\MESAPI\node_modules\async\lib\async.js:231:23)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000 }
[2018-12-10T14:25:11.040] [ERROR] dateFileLog - { Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjApp.js:218:14
    at D:\work\MESAPI\node_modules\async\lib\async.js:610:21
    at D:\work\MESAPI\node_modules\async\lib\async.js:249:17
    at iterate (D:\work\MESAPI\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (D:\work\MESAPI\node_modules\async\lib\async.js:165:9)
    at _asyncMap (D:\work\MESAPI\node_modules\async\lib\async.js:248:13)
    at Object.mapSeries (D:\work\MESAPI\node_modules\async\lib\async.js:231:23)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000 }
[2018-12-10T14:41:04.988] [ERROR] dateFileLog - { TypeError: D:\work\MESAPI\yujiang.Foil.Node.WebServer\app\system\sitemap\showSitemap.{v}.ejs:18
    16| 
    17| <div class="panel panel-default">
 >> 18| <div class="panel-heading">
    19|     <h3 class="panel-title">欢迎<%-(locals.session==null)?"什么？你居然跳过了登录界面？":locals.session.yjUser.AID%></h3>
    20| </div>
    21| <div class="panel-body">

Cannot read property 'AID' of undefined
    at eval (eval at exports.compile (D:\work\MESAPI\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:470)
    at eval (eval at exports.compile (D:\work\MESAPI\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1897)
    at D:\work\MESAPI\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\MESAPI\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\MESAPI\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\MESAPI\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\MESAPI\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\MESAPI\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\MESAPI\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\MESAPI\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\MESAPI\\yujiang.Foil.Node.WebServer\\app\\system\\sitemap\\showSitemap.{v}.ejs' }
[2018-12-10T15:53:13.334] [ERROR] dateFileLog - { Error: [Microsoft][SQL Server Native Client 11.0]未准备关联语句
  sqlstate: 'HY007',
  code: 0,
  sql: ' select a.MKOrdNO,b.Action from prdMKOrdMain a,(select PKValue,Action from comChangeLog where   changetime>= DATEADD(minute,-5, GETDATE()+2)) b where a.MKOrdNO=b.PKValue ' }
[2018-12-10T15:53:13.339] [ERROR] dateFileLog - { Error: [Microsoft][SQL Server Native Client 11.0]未准备关联语句
  sqlstate: 'HY007',
  code: 0,
  sql: ' select a.MKOrdNO,b.Action from prdMKOrdMain a,(select PKValue,Action from comChangeLog where   changetime>= DATEADD(minute,-5, GETDATE()+2)) b where a.MKOrdNO=b.PKValue ' }
[2018-12-10T16:15:39.628] [ERROR] dateFileLog - Error: 'config.security.isNeedSession' must set to true.
    at module.exports (D:\work\MESAPI\yujiang.Foil.Node.WebServer\app\account\showLogin.{get}.{m}.js:4:16)
    at buildData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:187:6)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:129:5
    at Object.module.exports.read (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)
    at loadData (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:123:15)
    at rrnmv (D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:120:2)
    at D:\work\MESAPI\yujiang.Foil.Node\src\yjMVC.js:223:4
    at Layer.handle [as handle_request] (D:\work\MESAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\work\MESAPI\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\work\MESAPI\node_modules\express\lib\router\route.js:112:3)
[2018-12-10T17:00:00.893] [ERROR] dateFileLog - ReferenceError: CreateTime is not defined
    at success (D:\work\MESAPI\mesAPI\biz\auto\syncPrdMKOrdMain.js:111:56)
    at Object.exports.safeSuccess (D:\work\MESAPI\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\MESAPI\yujiang.Foil.Node\src\yjError.js:148:12)
    at checkResults (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.engine.sqlserver.js:139:19)
    at StreamEvents.<anonymous> (D:\work\MESAPI\yujiang.Foil.Node\src\yjDBService.engine.sqlserver.js:191:14)
    at emitNone (events.js:106:13)
    at StreamEvents.emit (events.js:208:7)
    at Immediate.<anonymous> (D:\work\MESAPI\node_modules\msnodesqlv8\lib\reader.js:91:22)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
